### ISSUE TITLE
Loader animation optimization

### ISSUE THREAD

**Issue by evermake** [metafates/Wallery#1]
Something is wrong here I think:

https://user-images.githubusercontent.com/53311479/153007343-dd6322bd-f1aa-4b3d-add5-ed6f44774353.mov

Safari 15.3 arm64

**Comment by metafates** [comment]
I'm aware about that. That because there are so much going on with layout rendering that it's just can't animate loader properly. The animation itself is OK ([check this](https://dribbble.com/shots/5878367-Loaders)). I guess I should stick to something simpler in that case... It works way better in Firefox tho
